list(
  APPEND
  PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/arc/arc_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/checkbox/checkbox_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/effectslider/effectslider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/grid/grid_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/header/header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon/icon_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/subtitle/subtitle_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/title/title_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/effect/effect_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/home/home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/c_repos_GUI_Design_Project_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/c_repos_GUI_Design_Project.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_SemiBold_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_SemiBold_ttf_data.c)